name: Claude Code

on:
  issues:
    types: [opened, assigned]
  issue_comment:
    types: [created]

jobs:
  claude:
    if: |
      (github.event_name == 'issues' && 
       (github.event.action == 'opened' || 
        (github.event.action == 'assigned' && contains(github.event.issue.assignees.*.login, 'claude-ai[bot]')))) ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.assignee.login == 'claude-ai[bot]' &&
       github.actor != 'claude-ai[bot]')
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}